#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 12 14:28:51 CDT 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim shift_sim_behav -key {Behavioral:shift:Functional:shift_sim} -tclbatch shift_sim.tcl -log simulate.log"
xsim shift_sim_behav -key {Behavioral:shift:Functional:shift_sim} -tclbatch shift_sim.tcl -log simulate.log

