#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Oct 30 20:40:02 CDT 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim align_sim_behav -key {Behavioral:align:Functional:align_sim} -tclbatch align_sim.tcl -log simulate.log"
xsim align_sim_behav -key {Behavioral:align:Functional:align_sim} -tclbatch align_sim.tcl -log simulate.log

